# Example Valet configuration for working with remote Helm charts

# Debug logging
debug: false

# Output file name
output: values.schema.json

# Telemetry configuration
telemetry:
  enabled: false
  exporterType: none

# Helm chart configuration for remote charts
helm:
  chart:
    # Chart name (e.g., "postgresql" or "nginx")
    name: postgresql
    # Chart version (e.g., "12.1.9" or "latest")
    version: 12.1.9
    # Registry configuration
    registry:
      # Registry URL
      # Examples:
      # - Bitnami: https://charts.bitnami.com/bitnami
      # - Prometheus Community: https://prometheus-community.github.io/helm-charts
      # - Ingress Nginx: https://kubernetes.github.io/ingress-nginx
      url: https://charts.bitnami.com/bitnami
      # Registry type: HTTP, HTTPS, or OCI (defaults to HTTPS if not specified)
      type: HTTPS
      # Allow insecure connections (not recommended for production)
      insecure: false
      # Authentication (optional) - for private registries
      auth:
        # Basic auth
        username: ""
        password: ""
        # Token-based auth (alternative to username/password)
        token: ""
      # TLS configuration (optional) - for custom certificates
      tls:
        # Skip TLS verification (not recommended)
        insecureSkipTLSVerify: false
        # Client certificate for mTLS
        certFile: ""
        keyFile: ""
        # Custom CA certificate
        caFile: ""