# Example Valet configuration with Helm chart support and metrics enabled
logLevel: info
context: operations
output: ./generated-schema.json

# Telemetry configuration with metrics enabled
telemetry:
  enabled: true
  serviceName: valet
  serviceVersion: 0.1.0
  exporterType: otlp
  otlpEndpoint: localhost:4317
  insecure: true
  sampleRate: 1.0
  # Prometheus metrics configuration
  metrics:
    enabled: true
    port: 9090
    path: /metrics

# Helm chart configuration
helm:
  chart:
    name: prometheus
    version: 25.27.0
    registry:
      url: https://prometheus-community.github.io/helm-charts
      type: HTTPS
      insecure: false